# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "Siarhei/sergcentoslamp"
  config.vm.box_version = "1.1"
  config.vm.provider'virtualbox' do |vb|

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  config.vm.network 'private_network', ip: '192.168.33.10'

end
  config.vm.provision "shell", inline: <<-SHELL


  sudo mkdir -p /var/www/01-demosite-static/html
  sudo mkdir -p /var/www/01-demosite-php/html
  sudo chmod 775 /var/www
  sudo chown -R root:vagrant /var/www/html
  sudo cp /vagrant/01-demosite-php/index.php /var/www/01-demosite-php/html
  sudo cp /vagrant/01-demosite-static/index.html /var/www/01-demosite-static/html
  sudo sed -i '/Listen 80/a Listen 81' /etc/httpd/conf/httpd.conf
  sudo cp /vagrant/web.conf /etc/httpd/conf.d/
  sudo systemctl restart httpd

  SHELL
end
