# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "Siarhei/sergdeb"
  config.vm.box_version = "1.1"
  config.vm.provider'virtualbox' do |vb|

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  config.vm.network 'private_network', ip: '192.168.33.10'

end
end
