---
- name: Configure centos_server_ansible
  hosts: all

  tasks:

    - name: create directory if they don't exist
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /var/www/01-demosite-static/html
        - /var/www/01-demosite-php/html

    - name: copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}" 
      loop:
        - { src: '/vagrant/01-demosite-static/index.html', dest: '/var/www/01-demosite-static/html/index.html' }
        - { src: '/vagrant/01-demosite-php/index.php', dest: '/var/www/01-demosite-php/html/index.php' }
        - { src: '/vagrant/web.conf', dest: '/etc/httpd/conf.d/web.conf' }

    - name:
      file:
        path: /var/www
        mode: 0775
        recurse: yes

    - name: Add Apache port 81
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 81'
        insertafter: '^Listen 80'
        line: 'Listen 81'
        state: present

    - name: Restart service httpd
      become: yes
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: httpd
