KEY_PUB       = File.read('./rsa/id_rsa.pub')

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false
  config.vm.synced_folder "./roles", "/etc/ansible/roles", type: "rsync"

  config.vm.define "jenkins.vm", primary: true do |jvm|
    jvm.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    jvm.vm.network "private_network", ip: "192.168.3.10"
    jvm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = "2"
      vb.name   = "jenkins.vm"
    end
  end

  config.vm.define "staging.vm" do |svm|
    svm.vm.network "forwarded_port", guest: 8888, host: 8889, host_ip: "127.0.0.1"
    svm.vm.network "private_network", ip: "192.168.3.12"
    svm.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus   = "1"
      vb.name   = "staging.vm"
    end
  end

    config.vm.define "production.vm" do |pvm|
    pvm.vm.network "forwarded_port", guest: 8888, host: 8890, host_ip: "127.0.0.1"
    pvm.vm.network "private_network", ip: "192.168.3.13"
    pvm.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus   = "1"
      vb.name   = "production.vm"
    end
  end

  config.vm.define "nexus.vm" do |nvm|
    nvm.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
    nvm.vm.network "private_network", ip: "192.168.3.11"
    nvm.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus   = "1"
      vb.name   = "nexus.vm"
    end
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "provisioning/playbook.yaml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.galaxy_roles_path = "/etc/ansible/roles"
    ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    ansible.extra_vars = {
      nexus_staging_production_password: "admin",
      ssh_rsa_pub: KEY_PUB
    }
  end
end
