---
- name: playbook
  hosts: master
  become: yes

  tasks:
    - name: Install other packages
      yum:
        pkg:
        - mc
        - nano
        state: present

    - name: Disable SELinux
      shell: |
        setenforce 0
        sed -i.bak 's/enforcing/disabled/g' /etc/selinux/config

    - name: past host_key_checking = no in ansible.cfg
      become: yes
      lineinfile:
        path: /etc/ansible/ansible.cfg
        insertafter: '\[defaults\]'
        line: host_key_checking = False

    - name: Add servers in hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.1.2 puppet master.puppet
          192.168.1.3 slave1.puppet
          192.168.1.4 slave2.puppet

    - name: Install epel
      dnf:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
        state: present

    - name: Add Puppet yum repository
      shell: |
        sudo dnf -y install https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
      args:
        executable: /bin/bash

    - name: Create file /etc/profile.d/mypuppet.ch
      file:
        path: /etc/profile.d/mypuppet.ch
        state: touch

    - name: Add path for sudo
      replace:
        path: /etc/sudoers
        regexp: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
        replace: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin'

    - name: Add path /opt/puppetlabs/puppet/bin
      blockinfile:
        path: /etc/profile.d/mypuppet.ch
        block: |
          export PATH=$PATH:/opt/puppetlabs/puppet/bin
          export PATH=$PATH:/opt/puppetlabs/bin

    - name: Install puppetserver
      yum:
        pkg:
        - git
        - puppetserver
        state: present

    - name: Change memory for puppetserver
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: '-Xms2g -Xmx2g'
        replace: '-Xms512m -Xmx512m'

    - name: Enable puppetserver service
      systemd:
        name: puppetserver
        enabled: yes

    - name: Create a directory /etc/puppetlabs/r10k
      file:
        path: /etc/puppetlabs/r10k
        state: directory
        mode: '0775'

    - name: Create file /etc/puppetlabs/r10k/r10k.yaml
      file:
        path: /etc/puppetlabs/r10k/r10k.yaml
        state: touch

    - name: Add config r10k
      blockinfile:
        path: /etc/puppetlabs/r10k/r10k.yaml
        block: |
          ---
          :cachedir: '/var/cache/r10k'
          :sources:
            :my-org:
              remote: 'https://github.com/serggarant/puppet_conf.git'
              basedir: '/etc/puppetlabs/code/environments'

    - name: Create a directory /var/cache/r10k
      file:
        path: /var/cache/r10k
        state: directory
        mode: '2775'

    - name: setup gem r10k
      shell: |
        /opt/puppetlabs/puppet/bin/gem install r10k
        /opt/puppetlabs/puppet/bin/r10k deploy environment -p

    - name: Config master.puppet
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          dns_alt_names = puppet,master.puppet
          [main]
          certname = master.puppet
          server = master.puppet
          environment = production
          runinterval = 1m

    - name: Create file /etc/puppetlabs/puppet/autosign.conf
      file:
        path: /etc/puppetlabs/puppet/autosign.conf
        state: touch

    - name: Insert config autosign.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/autosign.conf
        block: |
          *.puppet

    - name: restart puppetserver service
      systemd:
        state: restarted
        daemon_reload: yes
        name: puppetserver

    - name: enable puppet-agent service
      systemd:
        name: puppet
        enabled: yes

    - name: restart puppet-agent service
      systemd:
        state: restarted
        daemon_reload: yes
        name: puppet

    - name: play ansible on master
      shell: |
        ansible-playbook -i /vagrant/inventory/hosts /vagrant/slave.yaml
      args:
        executable: /bin/bash
