---
- name: Install soft master
  hosts: master
  become: yes
  tasks:

    - name: enable the Enterprise Linux 8 repository
      shell: |
        sudo yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm

    - name: Install Server Puppet and git
      shell: yum install -y puppetserver git



    - name: Create file /etc/profile.d/mypuppet.ch
      file:
        path: /etc/profile.d/mypuppet.ch
        state: touch

    - name: Add path for sudo
      replace:
        path: /etc/sudoers
        regexp: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
        replace: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin'

    - name: Add path /opt/puppetlabs/puppet/bin
      blockinfile:
        path: /etc/profile.d/mypuppet.ch
        block: |
          export PATH=$PATH:/opt/puppetlabs/puppet/bin
          export PATH=$PATH:/opt/puppetlabs/bin


    - name: Change memory for puppetserver
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: '-Xms2g -Xmx2g'
        replace: '-Xms512m -Xmx512m'


    - name: Create a directory /etc/puppetlabs/r10k
      file:
        path: /etc/puppetlabs/r10k
        state: directory
        mode: '0775'

    - name: Create file /etc/puppetlabs/r10k/r10k.yaml
      file:
        path: /etc/puppetlabs/r10k/r10k.yaml
        state: touch

    - name: Add config r10k
      blockinfile:
        path: /etc/puppetlabs/r10k/r10k.yaml
        block: |
          ---
          :cachedir: '/var/cache/r10k'
          :sources:
            :my-org:
              remote: 'https://github.com/serggarant/puppet_conf.git'
              basedir: '/etc/puppetlabs/code/environments'

    - name: Create a directory /var/cache/r10k
      file:
        path: /var/cache/r10k
        state: directory
        mode: '2775'

    - name: setup gem r10k
      shell: |
        /opt/puppetlabs/puppet/bin/gem install r10k
        /opt/puppetlabs/puppet/bin/r10k deploy environment -p


    - name: Create file /etc/puppetlabs/puppet/autosign.conf
      file:
        path: /etc/puppetlabs/puppet/autosign.conf
        state: touch

    - name: Insert config autosign.conf
      blockinfile:
        path: /etc/puppetlabs/puppet/autosign.conf
        block: |
          *.puppet


    - name: ADD hosts
      lineinfile:
        path: /etc/hosts
        line: "{{item}}"
      with_items:
         - '192.168.3.10 master.puppet'
         - '192.168.3.11 slave1.puppet'
         - '192.168.3.12 slave2.puppet'

    - name: ADD host puppetserver
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
         - server = master.puppet
         - autosign = true

    - name: Enable Puppet
      systemd:
        name: puppet
        enabled: yes
        state: started

    - name: Start Puppet
      systemd:
        state: started
        name: puppet



- name: Install soft slave
  hosts: slave
  become: yes
  tasks:

    - name: enable the Enterprise Linux 8 repository
      shell: |
        sudo yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm


    - name: Install Puppet agent
      shell: yum install -y puppet-agent

    - name: ADD hosts
      lineinfile:
        path: /etc/hosts
        line: '192.168.3.10 master.puppet puppet'

    - name: Make connect to puppet-server
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
         - '[agent]'
         - 'server = master.puppet'
         - 'runinterval = 1m'

    - name: Enable Puppet
      systemd:
        name: puppet
        enabled: yes
        state: started

    - name: Restart Puppet
      systemd:
        state: restarted
        daemon_reload: yes
        name: puppet
