---
- name: play
  hosts: slaves
  become: yes

  tasks:
    - name: Disable SELinux
      shell: |
        setenforce 0
        sed -i.bak 's/enforcing/disabled/g' /etc/selinux/config


    - name: Add servers in hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.1.2 puppet master.puppet
          192.168.1.3 slave1.puppet
          192.168.1.4 slave2.puppet
    - name:
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

    - name: Install epel
      dnf:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
        state: present

    - name: Add Puppet yum repository
      shell: |
        sudo dnf -y install https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
      args:
        executable: /bin/bash

    - name: Create file /etc/profile.d/mypuppet.ch
      file:
        path: /etc/profile.d/mypuppet.ch
        state: touch

    - name: Add path for sudo
      replace:
        path: /etc/sudoers
        regexp: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
        replace: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin'

    - name: Add path /opt/puppetlabs/puppet/bin
      blockinfile:
        path: /etc/profile.d/mypuppet.ch
        block: |
          export PATH=$PATH:/opt/puppetlabs/puppet/bin
          export PATH=$PATH:/opt/puppetlabs/bin

    - name: install puppet-agent
      yum:
        pkg:
         - puppet-agent
        state: present

    - name: enable puppet service
      systemd:
        name: puppet
        enabled: yes


- name: slave1 play
  hosts: slave1
  become: yes

  tasks:
    - name: Insert config puppet-agent slave1
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [main]
          certname = slave1.puppet
          server = master.puppet
          environment = production
          runinterval = 1m

- name: slave2 play
  hosts: slave2
  become: yes

  tasks:
    - name: Insert config puppet-agent slave2
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [main]
          certname = slave2.puppet
          server = master.puppet
          environment = production
          runinterval = 1m


- name: Slaves play part2
  hosts: slaves
  become: yes

  tasks:
    - name: enable puppet-agent service
      systemd:
        name: puppet
        enabled: yes

    - name: restart puppet-agent service
      systemd:
        state: restarted
        daemon_reload: yes
        name: puppet
