# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
  	vb.memory = 1024
  	vb.cpus = 1
  end
  config.vm.define "slave1.puppet"  do |slave|
    slave.vm.network "public_network", ip: "192.168.1.3"
    slave.vm.network "forwarded_port", guest: 80, host: 8080
    slave.vm.hostname = "slave1.puppet"
  end
  config.vm.define "slave2.puppet"  do |slave|
    slave.vm.network "public_network", ip: "192.168.1.4"
    slave.vm.network "forwarded_port", guest: 81, host: 8081
    slave.vm.hostname = "slave2.puppet"
  end

  config.vm.define "master.puppet"  do |master|
    master.vm.network "public_network", ip: "192.168.1.2"
    master.vm.hostname = "master.puppet"
    master.vm.provision :file, source: '.vagrant/machines/slave1/virtualbox/private_key', destination: '/home/vagrant/private_key_slave1'
    master.vm.provision :file, source: '.vagrant/machines/slave2/virtualbox/private_key', destination: '/home/vagrant/private_key_slave2'
    master.vm.provision "shell", inline: <<-SHELL
    sudo chmod =600 /home/vagrant/private_key_slave1
    sudo chmod =600 /home/vagrant/private_key_slave2

    SHELL
    master.vm.provision :ansible_local do |ansible|
      ansible.playbook          = "playbook.yaml"
      ansible.limit             = "all"
      ansible.become            = true
      ansible.inventory_path    = "/vagrant/inventory/hosts"
    end
  end
end
