# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
  	vb.memory = 1024
  	vb.cpus = 1
  end

  config.vm.define "slave1"  do |slave1|
    slave1.vm.network "public_network", ip: "192.168.1.3"
    slave1.vm.network "forwarded_port", guest: 80, host: 8080
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
    SHELL
  end
  config.vm.define "slave2"  do |slave2|
    slave2.vm.network "public_network", ip: "192.168.1.4"
    slave2.vm.network "forwarded_port", guest: 81, host: 8081
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
    SHELL
  end

  config.vm.define "master"  do |master|
    master.vm.network "public_network", ip: "192.168.1.2"
    master.vm.hostname = "master.puppet"
    master.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yaml'
    ansible.inventory_path = "./inventory/hosts"
    end
  end
end
