version: '3'
services:
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 8081:8081
    networks:
      - serg
    container_name: nexus

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 80:8080
    networks:
      - serg
    container_name: jenkins
networks:
  serg:
